### PR TITLE
Upgrade to Faraday 1.x

### PR DESCRIPTION
**Pull request by jas14**

### CODE REVIEW

**Comment by jcoyne** [comment]
Thanks for submitting this @jas14. I'm going to test this.

**Comment by jcoyne** [comment]
This would fix #160

**Comment by dazuma** [comment]
Hi, sorry for the delay. Adding support for 1.x while continuing to allow for 0.x would make it easier for people to upgrade if they have other related dependencies. For example,
```ruby
gem.add_runtime_dependency "faraday", ">= 0.9", "< 2.0"
```

**Comment by jas14** [comment]
No worries, thanks for reviewing. I've just relaxed the restriction to `>= 0.17.3, < 2.0`, which allows only the last 0.x Faraday release. Let me know if we should relax that even more to e.g. `>= 0.9`, which was your original suggestion.

**Pull request merged**
