### PR TITLE
Handle unexpected status errors

### PR DESCRIPTION
**Pull request by ylecuyer**
Currently unexpected status errors return a Signet::AuthorizationError which is misleading

I added a Signet::UnexpectedStatusError so they can be distinguished

### CODE REVIEW

**Comment by ylecuyer** [comment]
@JustinBeckwith can't we merge this one ? it is the same as #100

**Comment by TheRoyalTnetennba** [comment]
Can you resolve the merge conflicts? Also, could you submit a corresponding PR to https://github.com/google/google-api-ruby-client? Check out this related PR: https://github.com/google/google-api-ruby-client/pull/707.  Specifically, the changes in http_command.rb.

**Comment by ylecuyer** [comment]
Merge conflict has been resolved. I'll ping you once the PR to google/google-api-ruby-client is made.
Thanks

**Comment by ylecuyer** [comment]
@TheRoyalTnetennba can this be merged ?

**Comment by ylecuyer** [comment]
As I understand it, googleapis/google-api-ruby-client#711 needs this PR to be green and won't be merged unless green.
And this PR needs googleapis/google-api-ruby-client#711 to be merged before getting merged.

What should I do then ?

**Comment by TheRoyalTnetennba** [comment]
Can you set the version to 0.10.0?

**Comment by ylecuyer** [comment]
done

**Pull request merged**
